Repository pulumi/pulumi-digitalocean, pull requests merged in 2019-06, with the labels that each got.

#9 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#10 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/cdn.ts
  sdk/nodejs/certificate.ts
  sdk/nodejs/databaseCluster.ts
  sdk/nodejs/dnsRecord.ts
  sdk/nodejs/domain.ts
  sdk/nodejs/droplet.ts
  sdk/nodejs/dropletSnapshot.ts
  sdk/nodejs/firewall.ts
  sdk/nodejs/floatingIp.ts
  sdk/nodejs/floatingIpAssignment.ts
  sdk/nodejs/kubernetesCluster.ts
  sdk/nodejs/kubernetesNodePool.ts
  sdk/nodejs/loadBalancer.ts
  sdk/nodejs/project.ts
  sdk/nodejs/provider.ts
  sdk/nodejs/spacesBucket.ts
  sdk/nodejs/sshKey.ts
  sdk/nodejs/tag.ts
  sdk/nodejs/volume.ts
  sdk/nodejs/volumeAttachment.ts
  sdk/nodejs/volumeSnapshot.ts
Labels: area/providers

#11 Addition of a mixin for DigitalOcean regions
  CHANGELOG.md
  examples/droplet/index.ts
  examples/floatingip/index.ts
  examples/loadbalancer/index.ts
  resources.go
  sdk/nodejs/databaseCluster.ts
  sdk/nodejs/droplet.ts
  sdk/nodejs/index.ts
  sdk/nodejs/kubernetesCluster.ts
  sdk/nodejs/loadBalancer.ts
  sdk/nodejs/region.ts
  sdk/nodejs/spacesBucket.ts
  sdk/nodejs/tsconfig.json
  sdk/nodejs/volume.ts
Labels: enhancement

#15 Fixing an issue with the publish-plugin script
  CHANGELOG.md
  scripts/publish-plugin.sh
Labels: bug

#18 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#20 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required

#16 Add the ability to set an explicit domain name property
  CHANGELOG.md
  examples/databaseCluster/index.ts
  examples/domain/index.ts
  examples/droplet/index.ts
  examples/floatingip/index.ts
  examples/loadbalancer/index.ts
  resources.go
  sdk/go/digitalocean/domain.go
  sdk/nodejs/dnsRecord.ts
  sdk/nodejs/domain.ts
  sdk/python/pulumi_digitalocean/domain.py
Labels: enhancement
